export const mockProperties = [
  {
    id: '1',
    title: 'Beautiful 3-Bedroom Apartment with Ocean Views with sea view',
    price: 7500,
    pricePerPeriod: 'month',
    currency: 'DH',
    propertyType: 'Apartment',
    bedrooms: 3,
    bathrooms: 2,
    area: 78,
    location: 'Casablanca, Ain Diab',
    locationId: '1',
    images: ['/images/light-styled-interior.jpg', '/images/cozzy-styled-interior.jpg'],
    isFavorite: false,
    phone: '0600000000',
    whatsapp: '+212600000000',
    email: 'test@test.com',
  },
  {
    id: '2',
    title: 'Modern Apartment in Prime Location',
    price: 8500,
    pricePerPeriod: 'month',
    currency: 'DH',
    propertyType: 'Apartment',
    bedrooms: 2,
    bathrooms: 1,
    area: 65,
    location: 'Rabat, Agdal',
    locationId: '1',
    images: ['/images/light-styled-interior.jpg', '/images/light-styled-interior.jpg'],
    isFavorite: true,
    phone: '0600000000',
    whatsapp: '+212600000000',
    email: 'test@test.com',
  },
  {
    id: '3',
    title: 'Luxury Villa with Private Pool and Garden',
    price: 25000,
    pricePerPeriod: 'month',
    currency: 'DH',
    propertyType: 'Villa',
    bedrooms: 5,
    bathrooms: 4,
    area: 350,
    location: 'Marrakech, Palmeraie',
    images: [
      '/images/light-styled-interior.jpg',
      '/images/light-styled-interior.jpg',
      '/images/light-styled-interior.jpg',
    ],
    isFavorite: false,
    phone: '0600000000',
    whatsapp: '+212600000000',
    email: 'test@test.com',
  },
  {
    id: '4',
    title: 'Spacious Family House with Large Terrace',
    price: 12000,
    pricePerPeriod: 'month',
    currency: 'DH',
    propertyType: 'House',
    bedrooms: 4,
    bathrooms: 3,
    area: 200,
    location: 'Casablanca, Maarif',
    locationId: '1',
    images: ['/images/light-styled-interior.jpg', '/images/light-styled-interior.jpg'],
    isFavorite: true,
    phone: '0600000000',
    whatsapp: '+212600000000',
    email: 'test@test.com',
  },
  {
    id: '5',
    title: 'Cozy 2-Bedroom Apartment in City Center',
    price: 6000,
    pricePerPeriod: 'month',
    currency: 'DH',
    propertyType: 'Apartment',
    bedrooms: 2,
    bathrooms: 1,
    area: 55,
    location: 'Tangier, Old Medina',
    locationId: '1',
    images: [
      '/images/light-styled-interior.jpg',
      '/images/light-styled-interior.jpg',
      '/images/light-styled-interior.jpg',
    ],
    isFavorite: false,
    phone: '0600000000',
    whatsapp: '+212600000000',
    email: 'test@test.com',
  },
  {
    id: '6',
    title: 'Premium Land for Development - 500m²',
    price: 1500000,
    pricePerPeriod: '',
    currency: 'DH',
    propertyType: 'Land',
    area: 500,
    location: 'Casablanca, Anfa',
    locationId: '1',
    images: ['/images/light-styled-interior.jpg', '/images/light-styled-interior.jpg'],
    isFavorite: false,
    phone: '0600000000',
    whatsapp: '+212600000000',
    email: 'test@test.com',
  },
  {
    id: '7',
    title: 'Elegant Villa with Sea View',
    price: 30000,
    pricePerPeriod: 'month',
    currency: 'DH',
    propertyType: 'Villa',
    bedrooms: 6,
    bathrooms: 5,
    area: 450,
    location: 'Casablanca, Ain Diab',
    locationId: '1',
    images: [
      '/images/light-styled-interior.jpg',
      '/images/light-styled-interior.jpg',
      '/images/light-styled-interior.jpg',
      '/images/light-styled-interior.jpg',
    ],
    isFavorite: true,
    phone: '0600000000',
    whatsapp: '+212600000000',
    email: 'test@test.com',
  },
  {
    id: '8',
    title: 'Traditional Moroccan House in Historic District',
    price: 10000,
    pricePerPeriod: 'month',
    currency: 'DH',
    propertyType: 'House',
    bedrooms: 3,
    bathrooms: 2,
    area: 150,
    location: 'Fez, Medina',
    locationId: '1',
    images: ['/images/light-styled-interior.jpg', '/images/light-styled-interior.jpg'],
    isFavorite: false,
    phone: '0600000000',
    whatsapp: '+212600000000',
    email: 'test@test.com',
  },
  {
    id: '9',
    title: 'Bright Office Space in Business District',
    price: 14600,
    pricePerPeriod: 'month',
    currency: 'DH',
    propertyType: 'Offices',
    area: 100,
    rooms: 2,
    bathrooms: 1,
    parkings: 5,
    location: 'Casablanca, Sidi Maârouf',
    locationId: '1',
    images: ['/images/light-styled-interior.jpg', '/images/light-styled-interior.jpg'],
    isFavorite: false,
    phone: '0600000000',
    whatsapp: '+212600000000',
    email: 'test@test.com',
  },
  {
    id: '10',
    title: 'Investment Land - Commercial Zone',
    price: 2500000,
    pricePerPeriod: '',
    currency: 'DH',
    propertyType: 'Land',
    area: 800,
    location: 'Casablanca, Sidi Maarouf',
    locationId: '1',
    images: ['/images/light-styled-interior.jpg'],
    isFavorite: false,
    phone: '0600000000',
    whatsapp: '+212600000000',
    email: 'test@test.com',
  },
  {
    id: '11',
    title: 'Penthouse Apartment with Panoramic Views',
    price: 15000,
    pricePerPeriod: 'month',
    currency: 'DH',
    propertyType: 'Apartment',
    bedrooms: 4,
    bathrooms: 3,
    area: 180,
    location: 'Casablanca, Corniche',
    locationId: '1',
    images: [
      '/images/light-styled-interior.jpg',
      '/images/light-styled-interior.jpg',
      '/images/light-styled-interior.jpg',
    ],
    isFavorite: true,
    phone: '0600000000',
    whatsapp: '0600000000',
    email: 'test@test.com',
  },
  {
    id: '12',
    title: 'Modern Villa with Contemporary Design',
    price: 22000,
    pricePerPeriod: 'month',
    currency: 'DH',
    propertyType: 'Villa',
    bedrooms: 4,
    bathrooms: 3,
    area: 280,
    location: 'Rabat, Hay Riad',
    locationId: '2',
    images: ['/images/light-styled-interior.jpg', '/images/light-styled-interior.jpg'],
    isFavorite: false,
    phone: '0600000000',
    whatsapp: '+212600000000',
    email: 'test@test.com',
  },
];


