import { Property } from '@/types/propery-details';

export const mockPropertyDetail: Property = {
  id: '1',
  basicInfo: {
    title: 'Beautiful 3-Bedroom Apartment with Ocean Views with sea view',
    transactionType: 'Rent',
    propertyType: 'Apartment',
    rooms: 3,
    bathrooms: 2,
    area: 120,
    location: {
      city: 'Casablanca',
      district: 'Ain Diab',
      fullAddress: 'Casablanca, Ain Diab',
    },
  },
  pricing: {
    price: 8500,
    currency: 'DH',
    pricePeriod: 'per month',
    isNegotiable: true,
    deposit: {
      amount: 1,
      period: 'month',
    },
    syndicFees: {
      amount: 1200,
      currency: 'DH',
      period: 'per month',
    },
    availableFrom: '2024-02-15',
  },
  description:
    'Discover this exceptional 3-bedroom apartment located in the prestigious Marina district of Casablanca. This stunning property offers breathtaking panoramic views of the Atlantic Ocean and the city skyline. The apartment features a modern open-plan living area with floor-to-ceiling windows that flood the space with natural light. The fully equipped gourmet kitchen boasts premium appliances and sleek finishes, perfect for culinary enthusiasts. The master bedroom includes a walk-in closet and an en-suite bathroom with luxurious fixtures. Two additional bedrooms offer comfort and style, ideal for family or guests. The apartment also features a spacious balcony overlooking the ocean, perfect for enjoying morning coffee or evening sunsets. Located in a secure building with 24/7 concierge service, this property represents the epitome of luxury living in Casablanca.',
  details: {
    floor: 8,
    totalArea: 165,
    livingArea: 145,
    ceilingHeight: 3.2,
    parkingSpaces: 1,
    windowView: 'Sea view',
  },
  building: {
    yearBuilt: '1-5 years',
    condition: 'Excellent',
    propertyClass: 'Luxury',
    renovation: 'Fully renovated',
    totalFloors: 12,
  },
  specialConditions: {
    petsAllowed: true,
    smokingAllowed: false,
    disabledAccess: false,
  },
  amenities: [
    { id: '1', name: 'Wi-Fi' },
    { id: '2', name: 'Heating' },
    { id: '3', name: 'Washing Machine' },
    { id: '4', name: 'TV' },
    { id: '5', name: 'Air Conditioning' },
    { id: '6', name: 'Equipped Kitchen' },
    { id: '7', name: 'Furnished' },
    { id: '8', name: 'Parking' },
    { id: '10', name: 'Balcony' },
    { id: '11', name: 'Terrace' },
    { id: '12', name: 'Swimming Pool' },
    { id: '13', name: 'Gym' },
    { id: '14', name: 'Security' },
  ],
  photos: [
    '/images/light-styled-interior.jpg',
    '/images/cozzy-styled-interior.jpg',
    '/images/kitchen-interior.png',
    '/images/cozzy-livingroom-interior.jpg',
    '/images/light-styled-interior.jpg',
    '/images/cozzy-styled-interior.jpg',
  ],
  agent: {
    id: 'agent-1',
    name: 'Sarah Benali',
    title: 'Agent',
    company: {
      name: 'Casablanca Premium Properties Lounge',
      logo: '/images/agency_logo.svg',
      logoText: 'bon ton',
    },
    contacts: {
      phone: '0600000000',
      whatsapp: '+212600000000',
      email: 'sarah.benali@example.com',
    },
    showContactsByDefault: false,
  },
  similarProperties: [
    {
      id: '2',
      title: 'Spacious villa with garden',
      location: {
        city: 'Rabat',
        district: 'Hay Riad',
        fullAddress: 'Rabat, Hay Riad',
      },
      price: 15000,
      currency: 'DH',
      pricePeriod: 'per month',
      rooms: 4,
      bathrooms: 3,
      area: 250,
      mainImage: '/images/light-styled-interior.jpg',
      propertyType: 'Villa',
      tags: ['Villa'],
      isFavorite: false,
      hasVideo: false,
      url: '/property/2',
    },
    {
      id: '3',
      title: 'Beautiful 3-Bedroom Apartment...',
      location: {
        city: 'Casablanca',
        district: 'Ain Diab',
        fullAddress: 'Casablanca, Ain Diab',
      },
      price: 8500,
      currency: 'DH',
      pricePeriod: 'per month',
      rooms: 3,
      bathrooms: 2,
      area: 120,
      mainImage: '/images/light-styled-interior.jpg',
      propertyType: 'Apartment',
      tags: ['Apartment'],
      isFavorite: true,
      hasVideo: true,
      url: '/property/3',
    },
    {
      id: '4',
      title: 'Furnished studio downtown',
      location: {
        city: 'Marrakech',
        district: 'Gueliz',
        fullAddress: 'Marrakech, Gueliz',
      },
      price: 4200,
      currency: 'DH',
      pricePeriod: 'per month',
      rooms: 1,
      bathrooms: 1,
      area: 45,
      mainImage: '/images/light-styled-interior.jpg',
      propertyType: 'Apartment',
      tags: ['Apartment'],
      isFavorite: false,
      hasVideo: false,
      url: '/property/4',
    },
  ],
};
